### ISSUE TITLE
[Perf] optimize the perf tests

### ISSUE THREAD

**Issue by huningxin** [huningxin/opencv#305]
1. reuse code as much as possible
2. allow to run multiple kernels in one page

**Comment by huningxin** [comment]
You can add `Sobel` kernel into the new perf test framework as an example.

**Comment by lionkunonly** [comment]
This is the simple introduction for the perf test of `Sobel`.

The perf for kernel `Sobel` is added. Please review it in the file `perf_sobel.html` nad `perf_sobel.js`. Because the parameters in the kernel `Sobel` is more than previous kernels, the number of test cases in `Sobel` is 2496. The declaration of kernel `Sobel` is:
```
cv.Sobel(src, dst, ddepth,  dx, dy, ksize, scale, delta, borderType);
```
I list the supported parameters setting and their own possible values:

|  param  | meaning |  possible values |
|---|---|---|
| size | the size of input parameters `src` and `dst`  | 640x480, 1280x720, 1920x1080 |
| matType | the mat type of input parameters `src` and `dst` | CV_8U, CV_16U, CV_16S, CV_32F, CV_64F | 
| ddepth  | the value of input parameter `ddepth` | CV_8U, CV_16U, CV_16S, CV_32F, CV_64F |
| direction | it determins the combination of `dx` and `dy` | dx (`dx=1`, `dy=0`),  dy(`dx=0`, `dy=1`) |
| ksize | it determins the value of `ksize` | k_1(`ksize = 1`), k_3(`ksize = 3`),  k_5(`ksize = 5`), k_7(`ksize = 7`)|
|  borderType | the value of input parameter `borderType` |  it is too long, pleace checkout the official doc|

One thing should be noted, the `CV_8U`, `CV_16U` does not appear in the official doc. In my implementation, it is allowed for some specific `matType` and represents the value `-1`. For example, when the `matType` is `CV_8U`, the `ddepth = CV_8U` is allowed and the input `ddepth` will be set as `-1` which is the official value. In this situation, the `CV_16U` is not allowed. For the Depth combinations, please check [https://docs.opencv.org/3.4/d4/d86/group__imgproc__filter.html#filter_depths](url)

**Comment by lionkunonly** [comment]
If you think the perf test for `Sobel` is ok, the issue can be closed.

**Comment by huningxin** [comment]
Thanks! It looks good. With the optimized perf tests, please continue to work on #304 .
