### ISSUE TITLE
[DNN] investigate js face recognition example

### ISSUE THREAD

**Issue by huningxin** [huningxin/opencv#321]
https://github.com/opencv/opencv/blob/master/samples/dnn/js_face_recognition.html

**Comment by huningxin** [comment]
@akineeic , we need to know:

1. how does the CMake system work for this js example?
2. what are the functions of this example?
3. how these functions are implemented?

Please help update your progress in this issue. Thanks!

**Comment by huningxin** [comment]
The js tutorial should showcase:

1. fetch model from network and save to emscripten fs (I/O)
2. load model into memory
3. blob from image and pre-processing
4. run model
5. post-processing and classification result
6. get performance data

@akineeic , please add js code snippets for these tasks.

**Comment by akineeic** [comment]
> @akineeic , please add js code snippets for these tasks.

I have divided code into several parts as follows:

- [x] 1 fetch model [code](https://github.com/huningxin/opencv/blob/b35568c9362de1af0ea0014bf290ef1b9e2f2aaa/doc/js_tutorials/js_assets/js_image_classification.html#L166-L180)

- [x] 2&4 run model [code](https://github.com/huningxin/opencv/blob/b35568c9362de1af0ea0014bf290ef1b9e2f2aaa/doc/js_tutorials/js_assets/js_image_classification.html#L183-L203)

- [x] 3 blob from image and pre-processing [code](https://github.com/huningxin/opencv/blob/b35568c9362de1af0ea0014bf290ef1b9e2f2aaa/doc/js_tutorials/js_assets/js_image_classification.html#L156-L163)

- [x] 5 post-processing [code](https://github.com/huningxin/opencv/blob/b35568c9362de1af0ea0014bf290ef1b9e2f2aaa/doc/js_tutorials/js_assets/js_image_classification.html#L206-L225)

- [x] 6 get performance data: I tried to bind `getPerfProfile` into opencv.js, but can't call it now.

But the functions haven't been put into the code snippets yet, since the functions declared in the code snippet seems can't be accessed by other snippets.

**Comment by huningxin** [comment]
please update the status and we can close this one.
