### ISSUE TITLE
[SIMD] The esmcripten version guard

### ISSUE THREAD

**Issue by huningxin** [huningxin/opencv#345]
As reported by @lionkunonly  in PR #342 , there are some WASM SIMD features are only supported in latest emscripten version (1.39.16) and not available in old version. So it means if merge it as is, there will be build errors for old version of emscripten. We may need to put emscripten version guard to handle this.

@terfendail , could you please check whether this is necessary from opencv team perspective. Thanks.

**Comment by terfendail** [comment]
I've discussed the situation with the team. it was decided it's a perfect time to update CI emscripten since actual version used for CI checks is quite old.
So version guard isn't necessary but it will be necessary to add information about required emscripten version to WASM intrinsics related pull request to main OCV repository.

**Comment by huningxin** [comment]
@lionkunonly , please follow up to add required emscripten version into the opencv.js build instrcutions. Created #347 to track this.
