### ISSUE TITLE
[WEBNN] Test cmake detect webnn with invalid path

### ISSUE THREAD

**Issue by huningxin** [huningxin/opencv#375]

**Comment by huningxin** [comment]
@MarkGHX , do you have any updates? Did you happen to test it?

**Comment by MarkGHX** [comment]
@huningxin Hi Ningxin, I have tested the codes in the webnn tflite delegate. However, the function webnnProcSetProcs() cannot be compiled successfully. To solve this, I first doubt that this is because webnn_proc.h is not included correctly. However, when I only left the codes #include<...>, the webnn.cpp can be compiled. And I also tried to change the include dirs to avoid potential conflicts, but the problem still existed. I don't know whether this is because my webnn-native is not compiled well. So I uploaded the new webnn.cpp and could you try it on your laptop? Thanks a lot!

Besides, I tried to compile the webnn.cpp using invalid path using the original codes. If I included a wrong head file or did not include WebnnNative.h, the code cannot be compiled correctly. Thus, this webnn.cpp can be used as an index to determine whether webnn-native is included.

**Comment by huningxin** [comment]
> @huningxin Hi Ningxin, I have tested the codes in the webnn tflite delegate. However, the function webnnProcSetProcs() cannot be compiled successfully. To solve this, I first doubt that this is because webnn_proc.h is not included correctly. However, when I only left the codes #include<...>, the webnn.cpp can be compiled. And I also tried to change the include dirs to avoid potential conflicts, but the problem still existed. I don't know whether this is because my webnn-native is not compiled well. So I uploaded the new webnn.cpp and could you try it on your laptop? Thanks a lot!

I believe this is fixed by #382 . Please help verify. If it is fixed, please close this issue. Thanks.

**Comment by MarkGHX** [comment]
Sorry for this late reply, since the lab was under cleaning today. The codes works on my laptop. Thanks a lot! After including libwebnn_proc.so, the MLContext can be initialized successfully.
