### ISSUE TITLE
Make PR to OpenCV

### ISSUE THREAD

**Issue by huningxin** [huningxin/opencv#56]
The PR to land js module to official opencv repo.

**Comment by huningxin** [comment]
@sajjadt , any updates on the OpenCV PR template? Thanks!

**Comment by sajjadt** [comment]
We have received few guidelines that I just share here. 

1. PR description should contain word "GSoC", project title and description of changes made, also it should mention student's mentor(s) (for ex. "@mshabuni"); it would be great to see some of results achieved (#[708](https://github.com/opencv/opencv_contrib/pull/708), #[752](https://github.com/opencv/opencv_contrib/pull/752), #[736](https://github.com/opencv/opencv_contrib/pull/736))
2. Branch from which PR is made should not be named "master" or "2.4", otherwise automated builds can fail; good branch names should be meaningful: "fix-aruco-issue", "fix_issue_9999", "gsoc/tests-for-aruco"

3. To test two or three pull requests submitted to opencv, opencv_contrib and opencv_extra together:
        push changes to branches with same name:
        git -C opencv push origin fix-9999
        git -C opencv_extra push origin fix-9999
        create PRs to these repositories
    pull request should be updated by pushing new commits to the same branch, no need to create a new one

Coding guidelines:
1. It is better to place algorithm implementation into an existing module if such exists, most of PRs should be made to the opencv_contrib repository; it is recommended to create new header and cpp files for each algorithm to minimize merge conflicts
    starting point in creation of new algorithm:
        declare an interface
        add a test creating the object or calling the function
        TEST(NewAlgorithm, basic) {
          Ptr<NewAlgorithm> p = NewAlgorithm::create();
          ASSERT_FALSE(p.empty());
        }
        add stubbed implementation to make test pass

[other guidelines](https://github.com/opencv/opencv/wiki/Coding_Style_Guide)

**Comment by huningxin** [comment]
postpone after M6

**Comment by pancx** [comment]
[GSoC Work Product Submission Guidelines](https://developers.google.com/open-source/gsoc/help/work-product)

**Comment by huningxin** [comment]
This issue is to track making the final PR to opencv.

**Comment by huningxin** [comment]
https://github.com/opencv/opencv/pull/9466
